add renderFooter function
Vitalii-Khivrych/team-project-filmoteka pull request #19
Opened 2022-07-04 11:31 UTC by parfors

Добавив розмітку футера у функцію і експортнув її у index.js

2022-07-04 12:09 UTC, dima-zharyy requested changes
1 замечание

2022-07-04 12:09 UTC, dima-zharyy commented on src/js/templates/render-footer.js
> +      <button href="" class="footer__button">GoIT Students</button>
тут нужно переделать на ссылку

2022-07-04 21:33 UTC, Vitalii-Khivrych approved these changes

2022-07-05 05:07 UTC, dima-zharyy approved these changes

2022-07-05 05:36 UTC, merged