Feature/ft 04
Vitalii-Khivrych/team-project-filmoteka pull request #8
Opened 2022-07-01 19:38 UTC by parfors

Добавив спрайт, прийми реквест, щоб зрозуміти чи моя проблема в цьому.
Потім пофікшу кнопку і перенос тексту.

2022-07-01 19:53 UTC, Vitalii-Khivrych requested changes

2022-07-01 19:53 UTC, Vitalii-Khivrych commented on src/partials/footer.html
> +      © 2020 | All Rights Reserved | Developed with<svg
Переделай как я показал

2022-07-01 19:53 UTC, Vitalii-Khivrych commented on src/sass/layout/_footer.scss
> +.footer__text {
добавь `display: inline;`

2022-07-02 10:48 UTC, parfors commented on src/sass/layout/_footer.scss
> +.footer__text {
Пофіксив

2022-07-02 10:49 UTC, parfors commented on src/partials/footer.html
> +      © 2020 | All Rights Reserved | Developed with<svg
Пофіксив, дивись

2022-07-02 13:19 UTC, Vitalii-Khivrych commented on src/sass/layout/_footer.scss
> +.footer__text {
На mobile вони невірно розташовані. Додай `р`ам маржини ліві та праві на mobile. На desktop змінюй їх.

2022-07-03 11:23 UTC, parfors commented on src/sass/layout/_footer.scss
> +.footer__text {
Зробив

2022-07-03 20:37 UTC, Vitalii-Khivrych approved these changes

2022-07-03 20:37 UTC, merged